phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - chmod +x ./gradlew
  build:
    commands:
      - ./gradlew build

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**
    - src/main/resources/static/** # <--- 이 줄 추가!
