version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew clean build -x test

  # πΆ μ¶”κ°€λ λ¶€λ¶„: νμΌλ… ν†µμΌ
  post_build:
    commands:
      - echo "Build completed on `date`"
      # λ²„μ „μ΄ λ¶™μ€ jar(μ: demo-0.0.1.jar)λ¥Ό app.jarλ΅ μ΄λ¦„ λ³€κ²½
      # (plain.jar μ μ™Έν•κ³  μ‹¤ν–‰ κ°€λ¥ν• jarλ§ μ„ νƒ)
      - mv build/libs/*-SNAPSHOT.jar build/libs/app.jar

artifacts:
  files:
    - build/libs/app.jar   # πΆ *.jar λ€μ‹  κ³ μ •λ μ΄λ¦„ μ‚¬μ©
    - appspec.yml
    - scripts/** # πΆ λ°°ν¬ μ¤ν¬λ¦½νΈ ν¬ν•¨
  # μ •μ  λ¦¬μ†μ¤(static)λ” JAR μ•μ— ν¬ν•¨λλ―€λ΅ μ μ™Έν–μµλ‹λ‹¤.
  discard-paths: yes       # (μ„ νƒ) S3 μ—…λ΅λ“ μ‹ κ²½λ΅ λ‹¨μν™”κ°€ ν•„μ”ν•λ©΄ yes, κµ¬μ΅° μ μ§€ν•λ ¤λ©΄ no