version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - chmod +x ./gradlew
      - ./gradlew --version
  build:
    commands:
      - ./gradlew clean build -x test
      - ls -la build/libs
artifacts:
  files:
    - build/libs/*.jar
