version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - chmod +x ./gradlew

  build:
    commands:
      - ./gradlew build \
        --parallel \
        --build-cache \
        -x test

cache:
  paths:
    - /root/.gradle/caches/**
    - /root/.gradle/wrapper/**

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**
    - src/main/resources/static/**
